[package]
name = "excel"
version = "0.1.0"
edition = "2021"

[dependencies]

serde_json = "1"
serde = { version = "1", features = ["derive"]}
rust_xlsxwriter = { version = "0.79.2", features = ["constant_memory"] }
flate2 = "1.0.34"
rayon = "1.5"

